### ISSUE TITLE
Multiple images in section

### ISSUE THREAD

**Issue by Constantin-Gololobov** [TimOetting/kirby-builder#10]
Hi, Tim!
Is it possible to add a multiple images to one section?

UPD:
Solved!

```
<?php
$images = $section->picture()->split();
foreach($images as $image): ?>
  <img src="<?php echo page()->image($image)->url() ?>">
<?php endforeach ?>
```

Thank you, Tim!

**Comment by Constantin-Gololobov** [comment]
Display multiple image in one section in admin panel:

**Blueprint:**
`entry: >
     <div class="post_image_stream" style="width: 50%; margin: 0 auto;">
          <div class="js_post_image_url">{{_fileUrl}}</div>
          <div class="js_post_image_name">{{picture}}</div>
</div>`

**JS:**
`$(function() {
var a = $(".post_image_stream");
a.html(function(b, e) {
var c = $(".js_post_image_name", this).text().split(","),
d = $(".js_post_image_url", this).text();
return c.map(function(a) {
var b = new Image;
b.src = d + a;
return b
})
})
});`

**Result:**
![screen shot 2016-02-11 at 20 07 53](https://cloud.githubusercontent.com/assets/1262756/12987175/35719ab0-d0fb-11e5-8020-1cf553216b77.png)

**Comment by SQbiz** [comment]
@Constantin-Gololobov does your blueprint have a set number of entries for images, or are you doing this with something like the http://getkirby-plugins.com/selector field?
