### ISSUE TITLE
nested builder field template example missing

### ISSUE THREAD

**Issue by theresa-g** [TimOetting/kirby-builder#100]
could you please add a quick example for a nested builder field template in the readme? as a beginner, i have trouble to accomplish it with only the example in the blueprint. how do i access the second layer of the builder in my template and do i need to nest a folder as well?

**Comment by jamiehunterdesign** [comment]
You should have the nested snippets in the same folder as their parents and use `foreach(**$data**->fieldName()->toBuilderBlocks() as $block):` to access it from within it's parent file. I was also struggling with this but I managed to get it working in this way.
