### ISSUE TITLE
explain how to get page object with $data->parent() in readme

### ISSUE THREAD

**Issue by bnomei** [TimOetting/kirby-builder#101]
might be obvious for those migrating from k2 or prior knowledge about structure but for everyone else this is a useful tip imho.

**Comment by TimOetting** [comment]
You could also just use the $page variable to access the page object. Or am I missing something?

**Comment by bnomei** [comment]
cant remember. to long ago. i think i had a onpager template iterting over blocks from different page objects. so inside the snippet the `$page` object would not be the current page object from the loop.

**Comment by TimOetting** [comment]
Okay. Not sure if this use case is a bit too special to be mentioned in the documentation. I guess I will therefore close this issue.

**Comment by bnomei** [comment]
ok but the parent function remains an undocumented feature then, right?
