### ISSUE TITLE
Switching languages in Kirby 3

### ISSUE THREAD

**Issue by flokosiol** [TimOetting/kirby-builder#103]
First of all: Thanks for this awesome plugin!

I had a strange issue in a **multi-language setup** does not seem to work properly. Switching the language the first time doesn't work, but afterwards the builder field **switches to the wrong language**.

Reloading the page brings the right content back (if you didn't save the wrong content before).

Sorry for this crappy GIF, but here you can see a normal text ("Test") field and below a builder field with a simple textarea block ("Modules").

![getkirbybuilderlanguages](https://user-images.githubusercontent.com/11918336/54499271-17da5600-4910-11e9-8be6-8e263fa2ac6c.gif)

It does not matter in which language I start nor which panel language is set for the current user.

**Comment by TimOetting** [comment]
Hey @flokosiol ,

could you please check out the latest version? I worked on how the content was handled after hitting the revert button to dismiss ontent changes. I think, your issue might be fixed as a side effect.

**Comment by flokosiol** [comment]
Thanks for the quick reply. I updated to the latest version 2.0.7 but unfortunately it does not solve the issue. I will check it with a fresh install and come back with a report 😉

**Comment by OlegIvaniv** [comment]
Hi @flokosiol, did you manage to reproduce this bug with a fresh install?

**Comment by flokosiol** [comment]
I‘m sorry. But I couldn’t find the time so far.

**Comment by flokosiol** [comment]
Alright, I finally checked it with the latest Starterkit (Kirby 3.1.1) and the latest Builder (2.0.7) and everything works as expected. 🤔 So it seems like there's a configuration in my setup which messes the language switch up. 

I close this issue. Sorry for the confusion …
