### ISSUE TITLE
The field type "builder" does not exist

### ISSUE THREAD

**Issue by eboehnisch** [TimOetting/kirby-builder#104]
I've switched to Kirby 3 in a separate subdomain (folder) until everything worked. Today I pushed everything to the website's master branch on GitHub and pulled to the designated folder for the final domain. I have added Kirby Builder as a submodule.

Now for the final domain the frontent works flawlessly but the panel throws this error:

`The field type "builder" does not exist`

When I disable the Builder plugin the frontend crashes and the backend shows `Invalid field type ("builder")` which is all expected. So the plugin in itself works and is loaded.

Similar to https://github.com/TimOetting/kirby-builder/issues/71 just moving Builder out of the `Plugins` directory and back in does not do the trick. Any ideas?

**Comment by eboehnisch** [comment]
Whoops, and just waiting for an hour cured the problem. Does Kirby update its plugin caches or compiled files on a schedule?

**Comment by TimOetting** [comment]
Hm, strange. The Plugin utilises the cache to store previews, but I cannot imagine that this is the reason for your problem here. 

For now, I will close this issue. Let me know if you have a similar problem again.

**Comment by moritzebeling** [comment]
Had the same problem and fixed it by using another PHP server, like:
`php -S localhost:8000 kirby/router.php`

**Comment by isUnknown** [comment]
I have the same problem since more than 1 hour and waiting had not cure anything for the moment…
Any idea ?
