### ISSUE TITLE
Composer installation

### ISSUE THREAD

**Issue by Kreativschnittstelle** [TimOetting/kirby-builder#108]
Hey guys,

first of all: awesome plugin - thanks a lot for your great work!

I am having an issue with the composer installation of the plugin. It seems not to get moved to "kirby-plugin-path" in my composer.json. Am I doing something wrong or is there really an issue?

Thanks and best,
Matthias

**Comment by kerli81** [comment]
I see that the changes are done on the master branch, but the tag for v2.0.8 is not yet done. As soon as someone creates a tag I expect the plugin will behave as expected regarding the installation folder.

**Comment by TimOetting** [comment]
The version has now been increased and the tag has been created. Can you check if your problem still exists?

**Comment by Kreativschnittstelle** [comment]
@TimOetting Hey, thanks for the update and your great plugin! Now it is installing to the right path, but I am still having problems, because the site doesn't load, when I choose a another directory than "vendor". I think it is not related to your plugin, but I am not sure.

**Comment by moddyn6** [comment]
@Kreativschnittstelle do you get an error message?
I see there is a fundamental problem with the composer install method as the new kirby composer installer removes the plugins vendor directory in the post-install process.
(see last paragraph in https://getkirby.com/docs/guide/plugins/plugin-setup-composer#support-for-plugin-installation-without-composer)

If this is a different bug from yours I will create a seperate issue

**Comment by luxlogica** [comment]
@TimOetting I think it's probably safe to close this issue - composer installation seems to be working as expected, and any remaining issues discussed here are probably not directly related to the composer install.

Just a small suggestion: it may be a good idea to remove the 'composer.lock' file from the repo - or add it to your .gitignore. I found that composer can get a bit confused when trying to solve dependencies if different plugins use different versions of Kirby core libraries in their composer.lock. I my case, I ended up with multiple duplicate copies of several Kirby class files - like "Api.php", "Api 2.php", "Api 3.php", etc. Also, when this happens composer will usually throw scary warnings to the user, saying that there are conflicting classes... In my own case, I found that deleting the composer.lock files stopped the problem from happening.

I suspect that the same thing probably applies to package-lock.json in the Vue world, but don't really know...

**Comment by TimOetting** [comment]
Closing this issue because this plugin will no longer be maintained, as its main functionality can be replaced by Kirby's built-in  [Blocks Field](https://getkirby.com/docs/reference/panel/fields/blocks) and [Layout Field](https://getkirby.com/docs/reference/panel/fields/layout).
