### ISSUE TITLE
Usage with snippets?

### ISSUE THREAD

**Issue by Andi-Lo** [TimOetting/kirby-builder#11]
Hi there,

i would like to know how i get the content in a site that uses snippet instead of templates for their sites. I builded my page as a one-pager  [(https://getkirby.com/docs/solutions/one-pager)](https://getkirby.com/docs/solutions/one-pager) and the call hirarchy is like: home.php->snippet-A.php>snippet->B.php

Using the example in your readme file suggests: 
```php
<?php foreach($page->builder()->toStructure() as $section): ?>

  <?php snippet('sections/' . $section->_fieldset(), array('section' => $section)) ?>
  
<?php endforeach ?>
```

but this will not give me the stored content, because I am not using templates for my site and thus the $page->builder() object /method is not able to fetch the data. The call hierarchy is like this:

Home.php builds
```php
<?php

snippet('header');
snippet('slider');

foreach($pages->visible() as $section) {
  snippet($section->uid(), array('data' => $section));
}

snippet('footer');

?>
```

snippet-A.php then calls:

snippet-A.php 
```php
foreach(page('example')->children()->visible() as $section):
	snippet($section->intendedTemplate(), array('data' => $data, 'section' => $section));
endforeach
```

Any ideas? I hope I could state my problem accordingly.
Greetings

**Comment by Andi-Lo** [comment]
figured it out thank you anyway.

**Comment by Thiousi** [comment]
Can you explain the solution you found?

**Comment by Andi-Lo** [comment]
Sure @Thiousi 
I do it something like this: My template (home.php) calls a snippet to build a section of my one pager.

/site/templates/yourtemplate.php
```php
<?php
	foreach($pages->visible() as $section) {
	   snippet($section->uid(), array('data' => $section));
   	}
?>
```

you can then access the $data object in your snippet and pass the data further to Snippet-B

**/site/snippets/snippetA.php**
```php
<?php
    foreach(page('somePage')->children()->visible() as $section):
       snippet($section->intendedTemplate(), array('data' => $data, 'section' => $section));
    endforeach
?>
```

Now I can use the $section object in my snippets like this:

**/site/snippets/snippetB.php**
```php
<?
    foreach($section->builder()->toStructure() as $section) {
        php snippet('sections/' . $section->_fieldset(), array('section' => $section));
    }
 ?>
```

In the **snippets/sections** you can now use the $section object:

**snippets/sections/contentimage.php**
```php
<p class="img-caption"><?php echo $section->caption()->kirbytextRaw() ?></p> 
```

Don't know if this is clear now. You can also take a look at this project where I am using it:
https://github.com/DigitalDesignIO/dmd-website/tree/master/app/site

Thats the call hirarchy
templates/home.php (then calls) -> snippets/hs.php (will build) -> snippets/contentblock.php (can have) -> snippets/sections/contentimage.php

**Comment by Thiousi** [comment]
That's a nice way of organizing a one-pager but I'd be afraid that a client could find it overwhelming. How has been the feedback you received?

And thanks a lot for sharing!

**Comment by Andi-Lo** [comment]
The feedback was great. They really appreciate the way kirby organizes the content and that you can relate between the content that you are viewing and the backend where you will fill it in.

In an earlier version the content was like a one pager so everything was in a huge long list. Then I realized we need more flexibility in structuring and organizing the content. To do this it couldn't be hard coded into the blueprint so I structured it more into a kinda component based approach.

**Comment by Thiousi** [comment]
That's great! I'll have to install your site on a local server to check out
how the panel feels like. Thanks again for sharing!
