### ISSUE TITLE
Option for visible/hidden blocks

### ISSUE THREAD

**Issue by findthebug** [TimOetting/kirby-builder#116]
An option to set a block visible/hidden would be nice. Right now i can add a block, but i can't set it to hidden. Maybe as an toggle option right to the dots or in the menu-list itself.

<img width="240" alt="Bildschirmfoto 2019-04-24 um 16 52 08" src="https://user-images.githubusercontent.com/5121132/56669368-543c6700-66b1-11e9-9e1b-07c71973c92c.png">

**Comment by TimOetting** [comment]
Hey @findthebug. There is the possibility to collapse blocks. Do you have a scenario where this is not enough? If the block would be completely hidden, you could not unhide it anymore because it is - well - hidden :) . Am I understand your feature request correctly?

**Comment by findthebug** [comment]
hidden is the wrong word, sorry. i mean publish / unpublish. so you can work within a unpublished block, and publish it later. or maybe a other person can publish the block after approval.

**Comment by dgsiegel** [comment]
My workaround for this is a field which is added to every block:

site/blueprints/fields/status.yml
```
label: Status
type: toggle
default: true
type: toggle
text:
  - Draft
  - Published
```

This can be included in all blocks via:
```
status:
  extends: fields/status
```

Then you only need to check inside your block loop:
```
 <?php
foreach($page->builder()->toBuilderBlocks() as $block) {
  if ($block->status()->isTrue()) {
    snippet('blocks/' . $block->_key(), array('data' => $block));
  }
}
?>
```
But it would be great if this could be part of the plugin.

**Comment by findthebug** [comment]
i did it exactly like that. this is a nice workaround solution but, you know, if the toggle is native-like in the menubar it would be perfekt.

**Comment by findthebug** [comment]
@TimOetting  wanted to ask whether this function still comes natively or not. we have a lot of customer demand for this feature. we are currently doing the workaround via a toggle, but it would be nicer if you could set it yourself on the module as suggested.

**Comment by ragi96** [comment]
@TimOetting well it would be pretty nice to have an option like this:
![module](https://user-images.githubusercontent.com/9362990/74828023-ab7d8900-530e-11ea-94cb-a13bf4a8713c.png)
Where the hidden Modules are just shown, for "user" which are logged in for the backend, and normal users dont see the hidden modules.

Thanks in advance.

**Comment by SirNovi** [comment]
The sortable plugin has this neat little menu bar that I wish every builder item would bring along as well. 
<img width="113" alt="Screen-Shot-2020-04-18-15-46-06-4638iyYbb9" src="https://user-images.githubusercontent.com/1991072/79639433-1e2ea780-818c-11ea-9773-c9855b89dc36.png">

**Comment by IvanConor** [comment]
@TimOetting I would agree with the guys above, it would be much cleaner a solution if it was plugin's native. Thank you!
