### ISSUE TITLE
Field called 'label' error

### ISSUE THREAD

**Issue by jimhaakman** [TimOetting/kirby-builder#117]
When a field is called 'label' you get an error `kirby array_merge(): Expected parameter 2 to be an array, null given` 

I think because it tries to read the value for translation through i18n. Only label inside a field should be checked for translation.

**Comment by findthebug** [comment]
check: https://github.com/TimOetting/kirby-builder/issues/127

**Comment by TimOetting** [comment]
Closing this issue because this plugin will no longer be maintained, as its main functionality can be replaced by Kirby's built-in  [Blocks Field](https://getkirby.com/docs/reference/panel/fields/blocks) and [Layout Field](https://getkirby.com/docs/reference/panel/fields/layout).
