### ISSUE TITLE
Sorting jump

### ISSUE THREAD

**Issue by jenstornell** [TimOetting/kirby-builder#12]
When I add images and sort them with drag and drop it first jumps down even if my mouse is still over the row. Look at this image. My image is far down on top of another kind of image field.

When draging some more it jumps back again.

![image](https://cloud.githubusercontent.com/assets/927011/13663049/165eabfe-e69f-11e5-8ae2-93b34dab8c16.png)

**Comment by dionysiusmarquis** [comment]
As the builder extends the kirby structure field it will also have all related issues. Can you try to double check if this also happens with your "entry: > " used in a kirby structure?

**Comment by jenstornell** [comment]
You are right. It was an issue with the structure field as well which means it got nothing to do with the builder field.
