### ISSUE TITLE
When installing with composer extra step needed

### ISSUE THREAD

**Issue by SinisaG** [TimOetting/kirby-builder#120]
Hi,

when installing the plugin with composer, there is no `vendor/autoload.php` when plugin is installed. 

```
PHP Fatal error:  require_once(): Failed opening required '/kirby/site/plugins/kirby-builder/vendor/autoload.php' (include_path='.:/usr/share/php') in /kirby/site/plugins/kirby-builder/index.php on line 2
```

To work around it, I then navigate to the plugin folder itself and trigger `composer build`. 

This is probably not how it should be - I might be missing something here?

Thanks for the help and all the work put in!

**Comment by TimOetting** [comment]
Hey @SinisaG ,

I thought that I solved this problem with the latest release. Are you installing version 2.0.11?

**Comment by SinisaG** [comment]
Hey @TimOetting ,

thanks for your quick reply. We were indeed running version `2.0.9`. I've now bumped it to `2.0.11` and all seem to be :ok_hand: . Thanks for the hint!
