### ISSUE TITLE
Dynamic block labels

### ISSUE THREAD

**Issue by dekodesign** [TimOetting/kirby-builder#121]
Of course please advise if there is already a way to do this... I would love to be able to include content from one of a block's fields (for example "title") in the block's label. Particularly when all blocks are collapsed, and there are many of the same block in use, it would be very helpful to be able to guide my users to open the correct one. Perhaps this would also @nilshoerrmann as an alternative to a global expand/contract. Thank you!

**Comment by LeBenLeBen** [comment]
Came here to open the exact same issue 😅

**Comment by TimOetting** [comment]
Hey there,

This feature has been added to the latest version. https://forum.getkirby.com/t/how-to-make-dynamic-label-from-field-in-blueprint/14307/6 . Please feel free to give me some feedback if this suits your needs.

**Comment by dekodesign** [comment]
Awesome, thank you!

**Comment by LeBenLeBen** [comment]
It works perfectly, thank you!
