### ISSUE TITLE
Duplicate-Button should not be visible if only one element is allowed

### ISSUE THREAD

**Issue by bavarianbytes** [TimOetting/kirby-builder#122]
Blueprint allows only one element:
```
label: Introbereich
type: builder
max: 1
``` 

But with "Duplicate" in the menu, it's possible to create more than one element:
<img width="917" alt="Bildschirmfoto 2019-05-15 um 08 48 21" src="https://user-images.githubusercontent.com/17915115/57754231-3aa9a080-76ee-11e9-870e-3aa86b4946fe.png">

**Comment by TimOetting** [comment]
Hey @bavarianbytes ,

Version 2.0.13 has just been released. The clone option does not appear anymore when the limit is reached.
