### ISSUE TITLE
index.js causes interference with other plugins

### ISSUE THREAD

**Issue by sylvainjule** [TimOetting/kirby-builder#126]
Hi Tim,

There seems to be an issue with the build process that crashes other parcel-bundled plugins (see https://github.com/sylvainjule/kirby-locator/issues/22 and https://github.com/sylvainjule/kirby-markdown-field/issues/76)

It seems fixed by adjusting the builder's build script to fit the [Pluginkit](https://github.com/getkirby/pluginkit/tree/4-panel) guidelines, meaning :

- Renaming `src/main.js` as `src/index.js`
- Changing the build script in `package.json` for:

```bash
parcel build src/index.js --no-source-maps --experimental-scope-hoisting -d ./
```

No idea of what is wrong with the current  build process, but everything works nicely together again after that 🤷‍♂️

**Comment by LeBenLeBen** [comment]
I confirm this plugin is causing issues for me as well, because it doesn't include a semi-colon at the end of it's `index.js` file.

Relates to https://github.com/getkirby/kirby/issues/1931

**Comment by LeBenLeBen** [comment]
According to my test, the build command doesn't even have to be changed. I cloned the respository and ran `npm run build` which resulted in a proper minified `index.js` including a semi-colon at the end.

I think the plugin release process is just missing the `npm run build` step which results in the development files being published instead.

@TimOetting Could you please release a patch including the production-ready JS file?
