### ISSUE TITLE
Undefined index in Panel - name of builder-field

### ISSUE THREAD

**Issue by findthebug** [TimOetting/kirby-builder#133]
Kirby 3.2.3
Builder: 2.0.12

Panel throws **"Undefined index - name-builder-field"** in the panel, if a builder-field was removed from the blueprint, but it's still stored in the page/site .txt content file.

If you have a huge installation, and you have to remove a builder-field (or rename it in code) for some reason, you also have to remove all "fields" in the content .txt file as well, or remove the builder-field via panel before removing from code. in production this is not feasible because there may be dozens of fields. 

best case would be, to just ignore unused builder-files in content .txt in the panel.

![Bildschirmfoto 2019-08-13 um 08 43 35](https://user-images.githubusercontent.com/5121132/62920571-75cb7680-bda6-11e9-9ad3-05e0e34b7243.png)

**Comment by TimOetting** [comment]
hey @findthebug ,

Version 2.0.13 has just been released. This version should have solved your problem.

**Comment by findthebug** [comment]
error doesn't show up anymore in 2.0.13 but there is still an issue.

e.g.
 
first text-block, second image-block

![Bildschirmfoto 2019-08-15 um 16 26 33](https://user-images.githubusercontent.com/5121132/63101640-bdeec280-bf79-11e9-8bfd-3e69b6024ecb.png)

delete image-block field from .yml

![Bildschirmfoto 2019-08-15 um 16 26 55](https://user-images.githubusercontent.com/5121132/63101610-b0393d00-bf79-11e9-8a2c-1a1de3862ebe.png)

there's now 2 of the first "text-block" all though is still image-block in content folder. after saving the second one, it turns also to text-block in content. e.g. is there a non available block, he just grabs the first one and shows it.
