### ISSUE TITLE
Is it possible to define default entries?

### ISSUE THREAD

**Issue by moritzebeling** [TimOetting/kirby-builder#135]
Is it possible to define default entries? Blocks that are already there when a new page is being created, just like the [structure field](https://getkirby.com/docs/reference/panel/fields/structure#default-values)? I could’t find any info about it, so I am asking here. Would be a nice functionality.

(As a really stupid workaround, I thought of inserting the needed default fields within a hook..., but I was hoping to avoid that ;) )

Thanks for your answer!

**Comment by TimOetting** [comment]
Closing this issue because this plugin will no longer be maintained, as its main functionality can be replaced by Kirby's built-in  [Blocks Field](https://getkirby.com/docs/reference/panel/fields/blocks) and [Layout Field](https://getkirby.com/docs/reference/panel/fields/layout).
