### ISSUE TITLE
Does not respect style table

### ISSUE THREAD

**Issue by jenstornell** [TimOetting/kirby-builder#14]
When set to `style: table` it does not work like the structure field. The structure field in this case does not care about entry and just create a new column for each sub field.

The builder however still uses the entry feature, also in the table.

**In builder it looks like this:**

Expected would be that the image would be in the column here called "Entry". "Rubrik" would fall into the next column. "Under" into a new column after that and the uri in the last column after that.

![image](https://cloud.githubusercontent.com/assets/927011/13705524/87a9b3e6-e7a1-11e5-8551-5e4bcef21e77.png)

**Comment by dionysiusmarquis** [comment]
That's only doable if every filedset holds the exact same fields (what's the case in the structure field). The builder however is designed to reflect different fieldsets with complete different fields. Imagine ten different fieldsets with no fields in common. It would be impossible to arrange them horizontally. 

As shown in your screenshots is another case where a simple structure field may fit your needs better.

**Comment by jenstornell** [comment]
I see. Structure field does not support image preview.
