### ISSUE TITLE
[idea] add icon to bloc selection dialog

### ISSUE THREAD

**Issue by webravenz** [TimOetting/kirby-builder#140]
Hello,

could be nice to add an icon for a bloc, when adding a bloc in the selection dialog, to the left of k-list-item.

user could see easily bloc type instead of reading all labels

**Comment by TimOetting** [comment]
Closing this issue because this plugin will no longer be maintained, as its main functionality can be replaced by Kirby's built-in  [Blocks Field](https://getkirby.com/docs/reference/panel/fields/blocks) and [Layout Field](https://getkirby.com/docs/reference/panel/fields/layout).
