### ISSUE TITLE
Dragging blocks between nested blocks not possible

### ISSUE THREAD

**Issue by wout** [TimOetting/kirby-builder#145]
My setup is much like the one with events in your example. When I create a nested block inside a block with columns, I can not drag it out or drag it inside another block with columns. Is there a way to enable this? Ideally, I would like to be able to configure which block types any given builder is allowed to receive.

**Comment by TimOetting** [comment]
Closing this issue because this plugin will no longer be maintained, as its main functionality can be replaced by Kirby's built-in  [Blocks Field](https://getkirby.com/docs/reference/panel/fields/blocks) and [Layout Field](https://getkirby.com/docs/reference/panel/fields/layout).
