### ISSUE TITLE
Field "group" doesn't work in builder

### ISSUE THREAD

**Issue by ragi96** [TimOetting/kirby-builder#149]
Hey

The Field "group" isn't working within the builder

`The field type "group" does not exist`

Would be really nice, if that's gonna be fixed.

**Comment by medienbaecker** [comment]
Duplicate of https://github.com/TimOetting/kirby-builder/issues/89

**Comment by TimOetting** [comment]
Closing this issue because this plugin will no longer be maintained, as its main functionality can be replaced by Kirby's built-in  [Blocks Field](https://getkirby.com/docs/reference/panel/fields/blocks) and [Layout Field](https://getkirby.com/docs/reference/panel/fields/layout).
