### ISSUE TITLE
Layout problem in Kirby 2.3

### ISSUE THREAD

**Issue by tristantbg** [TimOetting/kirby-builder#15]
![capture d ecran 2016-04-26 a 11 28 17](https://cloud.githubusercontent.com/assets/4832038/14813768/8ae7e502-0ba3-11e6-8494-1424b8a48f46.png)

The styling of the builder is broken in the beta version of Kirby.

**Comment by TimOetting** [comment]
This seems not to be the case anymore since the release candidate of Kirby 2.3. But thanks anyways :)
