### ISSUE TITLE
slow snippet previews

### ISSUE THREAD

**Issue by bnomei** [TimOetting/kirby-builder#159]
i tried to preview ~80 objects (some raw some with resolution autoid). the server hardware is quiet powerful but each preview request slowed down the panel by initial 0.5 sec and 0.25 sec to fetch the request which forced me to use a plain structure instead.

@bastianallgeier you might consider this issue when porting this plugin to core. 

as an idea... using php and an iframe sounds cool but imho is not a performant solution. personally i would not mind to provide VUE snippets for previews and custom css.

**Comment by bnomei** [comment]
pretty much what https://github.com/sylvainjule/kirby-previews does but for builder and editor would be awesome.

**Comment by mynameisfreedom** [comment]
Good thing is that the preview option for Page Builder is not so important, it can really live without it. 
I am more concerned with the slow load when there is more than just 10 heavy blocks (without preview option).

**Comment by TimOetting** [comment]
Closing this issue because this plugin will no longer be maintained, as its main functionality can be replaced by Kirby's built-in  [Blocks Field](https://getkirby.com/docs/reference/panel/fields/blocks) and [Layout Field](https://getkirby.com/docs/reference/panel/fields/layout).
