### ISSUE TITLE
texteditor not working in kirby-builder

### ISSUE THREAD

**Issue by favger** [TimOetting/kirby-builder#162]
Hello, this is how I output when I run the "texteditor" plugin from within the builder. How can I fix. Thank you in advance.

![k-1](https://user-images.githubusercontent.com/25633595/82614094-aa8b1a80-9bcf-11ea-85bc-265484b5fd2a.png)
![k-2](https://user-images.githubusercontent.com/25633595/82614095-ab23b100-9bcf-11ea-98c9-d230965be6f8.png)

**Comment by mynameisfreedom** [comment]
You must add 
`pretty: false `
in Editor blueprint. Then it will work.

**Comment by favger** [comment]
@mynameisfreedom  thanks for helping.
