### ISSUE TITLE
Nested Builder

### ISSUE THREAD

**Issue by marco-land** [TimOetting/kirby-builder#166]
I've updated the kirby builder and now nested builder are not working anymore

**Comment by TimOetting** [comment]
Hey @marco-land ,

are there any errors in the browser's javascript console? Can you send me an example blueprint where the nesting does not work?

**Comment by marco-land** [comment]
Yeah there is a lot
`POST http://localhost:8000/api/kirby-builder/pages/projects/test/builderconfig 404 (Not Found)`

`{status: "error", message: "No route found for path: "kirby-builder/pages/proj…ts/test/builderconfig" and request method: "POST"", code: 404, exception: "Exception", key: null, …}`

`Uncaught (in promise) {status: "error", message: "No route found for path: "kirby-builder/pages/proj…ts/test/builderconfig" and request method: "POST"", code: 404, exception: "Exception", key: null, …}`

**Comment by TimOetting** [comment]
I think the bug should be fixed with version 2.0.15.

Just for the records: This error only occurred in subpages and not on a top-level page, right?

**Comment by TimOetting** [comment]
Closing this issue because this plugin will no longer be maintained, as its main functionality can be replaced by Kirby's built-in  [Blocks Field](https://getkirby.com/docs/reference/panel/fields/blocks) and [Layout Field](https://getkirby.com/docs/reference/panel/fields/layout).
