### ISSUE TITLE
How to create Plugin?

### ISSUE THREAD

**Issue by demlak** [TimOetting/kirby-builder#168]
Hi, i want to add a block to the builder (blueprint fieldset and html template and so on). 

Before i start adding everything directly into the directory structure, i wanted to ask if it is possible to build this as an addon/plugin in a single folder instead of kirby-wide blueprint-, snippets-, templates-, etc. folder?

thx in a advance

**Comment by TimOetting** [comment]
Hey @demlak ,

this is not possible yet but it might be something for the future to be added.
