### ISSUE TITLE
Nested fieldset not working on sup-pages

### ISSUE THREAD

**Issue by TobiasStill** [TimOetting/kirby-builder#169]
Api call to builderconfig from kirby-panel results in #404 on sub-pages. The builder does not work on sub-pages thus.

I debugged a bit and got a solution that works for me:
in index.php I changed the route from:
'pattern' => 'kirby-builder/pages/(:any)/builderconfig'
to
'pattern' => 'kirby-builder/pages/(:**all**)/builderconfig'

**Comment by TimOetting** [comment]
Hey @TobiasStill,

thanks for your help 🎖. Your fix has been added to the latest version of the builder.
