### ISSUE TITLE
Preview iframe not auto-sizing after update

### ISSUE THREAD

**Issue by something-strange** [TimOetting/kirby-builder#172]
Hey @TimOetting - this builder is amazing, thank you man!

I noticed a minor issue when using the preview option... for example, I have a textarea field in my blueprint. I add some copy, let's say 10 lines of copy. I click preview, and the iframe autosizes the height around copy nicely.

Then, I go back and edit my textarea copy. Let's say I take out 6 lines of copy, so now there are only 4 lines. When I go back to preview this, there's a larger (6 lines worth) of extra dead space - the iframe never updated to the new height.

**Comment by TimOetting** [comment]
Closing this issue because this plugin will no longer be maintained, as its main functionality can be replaced by Kirby's built-in  [Blocks Field](https://getkirby.com/docs/reference/panel/fields/blocks) and [Layout Field](https://getkirby.com/docs/reference/panel/fields/layout).
