### ISSUE TITLE
Use builder in an headless enviroment

### ISSUE THREAD

**Issue by brechtknecht** [TimOetting/kirby-builder#174]
Hey Tim,

currently i am trying to implement Kirby as a Headless CMS. Therefore i am using the [vue-kirby-starterkit](https://github.com/jmheretik/kirby-vue-starterkit) wich is quite foreward. 

The main difference between the standard kirby configuration and the vue-kirby-starterkit is that the template files dosen't output the data to the template itself. but rather putting it into a JSON. This JSON will be recieved from the frontend and will be processed by vue.

The Problem is, that `$page->myBuilder()` returns this JSON 

`{ "value": "- \n text: '[{\"attrs\":[],\"content\":\"TEST\",\"id\":\"_pljxwp67h\",\"type\":\"h1\"},{\"attrs\":[],\"content\":\"\",\"id\":\"_1hxha84wb\",\"type\":\"paragraph\"},{\"attrs\":[],\"content\":\"TEST\",\"id\":\"_3jieddjbn\",\"type\":\"paragraph\"}]'\n _key: bodytext\n _uid: bodytext_1596118658894_94\n- \n note:\n - notes/a-night-in-the-forest\n - notes/in-the-jungle-of-sumatra\n - notes/through-the-desert\n _key: Notes\n _uid: Notes_1596118888553_94\n- \n text: Testtesxt\n _key: test\n _uid: test_1596118945435_94" }`

I can see that the JSON contains my data but I can't get valid JSON data out of it. I tried to unescape the json but this made the JSON completely invalid. Do some of you have an approach to get this working?

**Comment by TimOetting** [comment]
Closing this issue because this plugin will no longer be maintained, as its main functionality can be replaced by Kirby's built-in  [Blocks Field](https://getkirby.com/docs/reference/panel/fields/blocks) and [Layout Field](https://getkirby.com/docs/reference/panel/fields/layout).
