### ISSUE TITLE
Feature Request: Compact UI

### ISSUE THREAD

**Issue by HYR** [TimOetting/kirby-builder#178]
Feature request for a `ui: compact` feature so that the user interface takes up as little space as possible. Especially useful for nested Builder fields.

**Comment by TimOetting** [comment]
Closing this issue because this plugin will no longer be maintained, as its main functionality can be replaced by Kirby's built-in  [Blocks Field](https://getkirby.com/docs/reference/panel/fields/blocks) and [Layout Field](https://getkirby.com/docs/reference/panel/fields/layout).
