### ISSUE TITLE
Value missing when cloning a block

### ISSUE THREAD

**Issue by chrfickinger** [TimOetting/kirby-builder#180]
Usually the fields _key and _uid are automatically created when creating a builder block.
By cloning a builder block a unique _uid field is not created, so the block has no unique identifier.

**Comment by TimOetting** [comment]
Closing this issue because this plugin will no longer be maintained, as its main functionality can be replaced by Kirby's built-in  [Blocks Field](https://getkirby.com/docs/reference/panel/fields/blocks) and [Layout Field](https://getkirby.com/docs/reference/panel/fields/layout).
