### ISSUE TITLE
No fields shown in Firefox and Chrome

### ISSUE THREAD

**Issue by seehat** [TimOetting/kirby-builder#188]
I can't get the fields to show up in Firefox and Chrome like the following screenshot: 

![Bildschirmfoto 2020-11-27 um 16 44 13](https://user-images.githubusercontent.com/818248/100465625-ed263600-30cf-11eb-9a82-56e38b7910b8.png)

I see no console errors. Just plain empty divs under the builder block headers. 
It's working properly in Safari.

Do you have an idea how this can be? 

CMS Version: 3.4.4
Builder-Version: 2.0.16
Chrome 87
Firefox 83

**Comment by bensanlau** [comment]
I had this happen to me from time to time. I resolved it by removing all the `kBuilder` keys in localStorage (or clear site data for that domain).

**Comment by seehat** [comment]
Wow thanks. This is the solution. But it's difficult to explain to the client. Thx!

**Comment by TimOetting** [comment]
Hey @seehat yes, that's true. This issue came up in between two versions of the plugin. I will need to add some mechanism to initially clear the local storage automatically with the next update.

@bensanlau thanks for your help here

**Comment by seehat** [comment]
Hey @TimOetting, this would be fine! Thanks for your reply!

**Comment by TimOetting** [comment]
Closing this issue because this plugin will no longer be maintained, as its main functionality can be replaced by Kirby's built-in  [Blocks Field](https://getkirby.com/docs/reference/panel/fields/blocks) and [Layout Field](https://getkirby.com/docs/reference/panel/fields/layout)
