### ISSUE TITLE
'Undefined Index: Key' when using a files field in a nested builder

### ISSUE THREAD

**Issue by baraglobal** [TimOetting/kirby-builder#194]
Kirby: 3.5.6
Builder: 2.0.16

When using nested builders, any effort to use a files field results in an error 'Undefined Index: [field key]'. It's not something I've encountered in the past so having some trouble pinpointing what could be causing it. Any help would be massively appreciated!

Example code:

        descriptionBuilder:
          label: Description Builder
          type: builder
          columns: 1
          fieldsets:

            descriptionBlock:
              name: Description Block
              label: '{{ model }} wears...'
              fields:

                model:
                  label: Model Name
                  type: text  

                garmentBuilder:
                  label: Garment Builder
                  type: builder
                  columns: 1
                  fieldsets:

                    garment:
                      name: Garment
                      label: Garment
                      fields:

                        garmentName:
                          label: Garment Name
                          type: text

                        garmentImage:
                          label: Garment Image
                          type: files
                          max: 1
![Screenshot 2021-06-09 at 11 50 43](https://user-images.githubusercontent.com/44905841/121342801-eb102000-c919-11eb-8610-a5ffb22ace67.png)

**Comment by TimOetting** [comment]
Closing this issue because this plugin will no longer be maintained, as its main functionality can be replaced by Kirby's built-in  [Blocks Field](https://getkirby.com/docs/reference/panel/fields/blocks) and [Layout Field](https://getkirby.com/docs/reference/panel/fields/layout)
