### ISSUE TITLE
When trying to add new blocks, Builder shows blank modal

### ISSUE THREAD

**Issue by exotexot** [TimOetting/kirby-builder#200]
Hello, 

For some reason the builder plugin shows me a blank addBlock modal.
It used to work in the past, and there were no changes from my side touching the builder code. 

Am I overseeing something?

![Screenshot 2022-04-08 at 17 16 55](https://user-images.githubusercontent.com/10153413/162472322-cf0bebb3-74db-467a-8b77-a0b11c878c5d.png)

**Comment by owzim** [comment]
@exotexot it is probably due to the fact that you're using Kirby `3.6.x` with which this plugin is no longer compatible anymore. Either use a Kirby version older than that, or use the new core [Blocks Field](https://getkirby.com/docs/reference/panel/fields/blocks) as a replacement.

**Comment by exotexot** [comment]
@owzim damn, thanks. Wasnt paying attention to that development.
