### ISSUE TITLE
This no longer works with multiple fieldsets

### ISSUE THREAD

**Issue by p-mylecharane** [TimOetting/kirby-builder#202]
This no longer works with multiple fieldsets after `"getkirby/cms": "3.4"`

I’ve wondered why when clicking to add a builder section on updated client sites, that nothing shows. I played around with installing different versions of kirby core, and found it works under `3.4`. It may have something to do with a combination of php versions also. I love this plugin, do you have any plans to pick it up again?

**Comment by TimOetting** [comment]
Closing this issue because this plugin will no longer be maintained, as its main functionality can be replaced by Kirby's built-in  [Blocks Field](https://getkirby.com/docs/reference/panel/fields/blocks) and [Layout Field](https://getkirby.com/docs/reference/panel/fields/layout)
