### ISSUE TITLE
Sunset the plugin and mention Blocks

### ISSUE THREAD

**Issue by iskrisis** [TimOetting/kirby-builder#203]
This plugin has lots traffic because of name "kirby builder" it would be good idea to point people to the core https://getkirby.com/docs/reference/panel/fields/blocks that replace the plugin.

@TimOetting maybe you could archive the repo and change the readme to mention Blocks?

**Comment by TimOetting** [comment]
Fair point. The Readme has been Updated and the Repo will now be archived.
