### ISSUE TITLE
Add section button option

### ISSUE THREAD

**Issue by Thiousi** [TimOetting/kirby-builder#21]
Would it be possible to have as an option a single button at the bottom of the sections "Add Section" for instance that would display all available sections in a dropdown?

Having for instance 20 sections to build a one-pager, it feels bad in terms of UX to display all 20 buttons.

**Comment by TimOetting** [comment]
Sounds like a good point. I will work on this asap.

**Comment by jesuismaxime** [comment]
Is this enhancement going somewhere finally ? (Kind of need it)

**Comment by TimOetting** [comment]
This issue is related to old version for Kirby 2 and will therefore not be fixed anymore. I am currently closing all the old reports to clean up the the issues section here on github.
