### ISSUE TITLE
Incorrect width setting after changing the order of an item

### ISSUE THREAD

**Issue by rzschoch** [TimOetting/kirby-builder#26]
Hi,

when changing the order of an item and trying to edit the changed one, the wrapping div container (builder-entry-quickform-container) gets an incorrect width of 0.

responsible code snippet (builder.js, line 38):

``` javascript
      helper: function(e, ui) {
        ui.children().each(function() {
            $(this).width($(this).width());
        });
        return ui.addClass('structure-sortable-helper');
      },
```

a working (nasty) solution:

``` javascript
      helper: function(e, ui) {
        ui.children().each(function() {
          var width = $(this).width();

          if (width !== 0) {
            $(this).width(width);
          }
        });
        return ui.addClass('structure-sortable-helper');
      },
```

**Comment by Thiousi** [comment]
This makes the section impossible to edit until the page is reloaded. I often just touch the section block when trying to click on edit and the same problem happens.

**Comment by olach** [comment]
Why was this width setting added in the first place? I removed the whole helper function without problems.

Actually this function is an option for the jQuery Sortable Widget that the builder field uses. The documentation for this helper function can be [found here](http://api.jqueryui.com/sortable/#option-helper).

I see no point of setting the width explicit when sorting the items. Removing it works just fine. But if the author knows why this was added in the first place you might add a comment here.

**Comment by olach** [comment]
Ok, without this helper function, the dragged item disappear sometimes. Looking at the documentation this helper function can return a DOM element to be used while dragging. The default setting is that the original item is being dragged. But using this helper function, a new DOM element is used instead.

Changing the helper function to this seems to be working fine for me now. Not necessary to set the width, but the helper function needs to return a new DOM element.

```js
helper: function(e, ui) {
    return ui.addClass('structure-sortable-helper');
},
```

**Comment by WeTurkstra** [comment]
I found that dragging an item but not changing its order in the builder list made the width stay at 0px.
After i added `app.content.reload();` to the stop function of the sortable it didn't seem to happen again. 
The only nasty thing is that when an item is dragged to a new position `app.content.reload()` is called twice.

**Comment by macx** [comment]
@TimOetting Could you please investigate this problem? The solution from @olach seams to be a quick fix that works.

**Comment by TimOetting** [comment]
This issue is related to old version for Kirby 2 and will therefore not be fixed anymore. I am currently closing all the old reports to clean up the the issues section here on github.
