### ISSUE TITLE
Prevent CMD+S/Strg+S

### ISSUE THREAD

**Issue by medienbaecker** [TimOetting/kirby-builder#27]
When editing a regular structure field in a modal the CMD+S/Strg+S shortcut does not trigger. This should definitely be the case for the builder field, too. Otherwise everything is lost when accidentally saving.
Even better than disabling the shortcut would be to trigger the "Ok" button of the open item.

**Comment by sakamies** [comment]
This applies to the buttons as well. Sometimes the save button is the most prominent button and the ok button is somewhere hidden.

![screen shot 2017-02-20 at 18 35 44](https://cloud.githubusercontent.com/assets/619780/23134026/e9b954be-f79b-11e6-8f48-0ce8dc2bc47c.png)

**Comment by TimOetting** [comment]
This issue is related to old version for Kirby 2 and will therefore not be fixed anymore. I am currently closing all the old reports to clean up the the issues section here on github.
