### ISSUE TITLE
Textarea has no formatting icons

### ISSUE THREAD

**Issue by joernba** [TimOetting/kirby-builder#3]
Hi,
somehow textareas inside a builder don't have formatting icons (bold, italic, etc.). Is that expected behaviour?
Keep up the great work.

Cheers.
Joern

**Comment by sen-zo** [comment]
Hi, 
this behaviour is inherited from Kirbys Structure field which is the basis for this plugin.

**Comment by joernba** [comment]
Ok. Thanks. I thought it might be a bug. :)
