### ISSUE TITLE
Textarea fields inside builder do not supper 'link' buttons.

### ISSUE THREAD

**Issue by louiswalch** [TimOetting/kirby-builder#30]
How come the link button doesn't work for textareas contained within a builder field?

**Comment by medienbaecker** [comment]
The builder was formally used with modals just like the core structure field. It's still not possible to open (another) modal in the builder, though. I **think** it has something to do with [this](https://forum.getkirby.com/t/plugin-for-an-extended-structure-field-with-more-then-one-kind-of-field-set/1696/54).

**Comment by dionysiusmarquis** [comment]
Yes, it's killed by kirby for all structure text fields because of the double modal problem. I'll take a look if its possible to reenable it for builder fields.

**Comment by dionysiusmarquis** [comment]
Ok, i tried it. It's possible to reactivate the textarea buttons and even the structure field inside the builder fieldset. Unfortunately the JavaScript urls linking to the explicit field doesn't support structures. It will end up in `http://mysite/panel/pages/projects/myproject/field/copy/textarea/link` but would need something like `http://mysite/panel/pages/projects/myproject/field/ SCOPE TO STRUCTURE /copy/textarea/link`.
Kirby doesn't handle this case at all, wich seems to be one reason its disabled in the first place.

**Comment by TimOetting** [comment]
This issue is related to old version for Kirby 2 and will therefore not be fixed anymore. I am currently closing all the old reports to clean up the the issues section here on github.
