### ISSUE TITLE
Builder does not seem to handle multi-lang labels in fieldset fields

### ISSUE THREAD

**Issue by texnixe** [TimOetting/kirby-builder#33]
Resutling in an "Array to string conversion" notice in line 30 of template.php:

```
 <?= $fieldset->label ?>
```

At the same time, multi-lang labels in fields themselves are ignored and only the fieldname itself is shown.

Multi-labels for the builder field itself, however, do work.

**Comment by ITforHome** [comment]
Any news about this case?

**Comment by TimOetting** [comment]
This issue is related to old version for Kirby 2 and will therefore not be fixed anymore. I am currently closing all the old reports to clean up the the issues section here on github.
