### ISSUE TITLE
414 Error when using long texts in structured field textarea

### ISSUE THREAD

**Issue by Andi-Lo** [TimOetting/kirby-builder#35]
Hello there,

I encountered an error in this plugin when using it with a long text e.g. some data-privacy rules or large chunks of imprint text with ~8000 characters.

This is what the error looks like:

```
http://example.com/panel/pages/datenschutz/2986…xt=&link=&text_align=left&csrf=81lBnk5FCbEW5TATMUeoPMzNDr4qteFz&_redirect= 
Failed to load resource: the server responded with a status of 414 (Request-URI Too Large)
```
Error message in Browser: 

#### The requested URL's length exceeds the capacity limit for this server.

So I guess you're passing all the content onto the url via a GET request and thus you exceed the max limit of characters an URI can have? The problem lays in this ajax call:

```javascript
    $.ajax({
      type: "POST",
      url: url + urlParamSeparator + data,
      success: function(){
        app.content.reload();
      }
    });
```

this appends all data to the url and thus exceeds the max URI length. I think the data should not be appended to the url but to the ajax data object.

**Comment by Andi-Lo** [comment]
Changing the ajax call to:

```javascript
    $.ajax({
      type: "POST",
      url: url + urlParamSeparator,
      data: data,
      success: function(){
        app.content.reload();
      }
    });
```
fixes the problem for me. I see there is already a pull request open which tackles the same problem:
"Submitting updated data by POST instead of GET #32"

**Comment by pkaso** [comment]
Hi Andi,
your solution is shorter and cleaner than my PR you referenced. Just be careful that you use Kirby 2.4.1 and newer. There was another bug in Kirby Panel that removed your data passed as String from ajax calls https://github.com/getkirby/panel/pull/945

Hopefully some fix will be made to kirby-builder plugin :)

m.

**Comment by Andi-Lo** [comment]
I see, thanks for the info I will consider upgrading to the latest version 👍

**Comment by fitzage** [comment]
This solution solved the problem for me as well (Kirby 2.4.1).

**Comment by macx** [comment]
@TimOetting This fix a no-brainer and works like a charme. Please update it!

**Comment by TimOetting** [comment]
Hey guys. The update has just been pushed. Thanks for the suggestions and pull request regarding this issue!
