### ISSUE TITLE
Confirm block changes on save

### ISSUE THREAD

**Issue by wout** [TimOetting/kirby-builder#37]
First of all, thanks for this plugin. It's a great addition to Kirby.

There is one point of frustration, though. Not only for me but also for other people working on our site. If you hit the Kirby save button before clicking OK on a block, the content and changes to that block are lost. And this happens a lot because sometimes the OK button is located outside of the viewport while the save button is promptly showing at the bottom of the page.

Off the top of my head, I can think of two solutions. Either hide the save button so you can't do anything else but clicking on the save button first. Or just hook into the save event somehow and register the changes before submitting the data.

**Comment by TimOetting** [comment]
Hey wout,

what version of kirby are you using? The first solution you provided is already implemented. The save button is hidden while being in the edit mode of an entry. You can see it in the gif animation of the project's readme. Or am I missing something?

**Comment by wout** [comment]
Hi,

I'm using the latest version so it seems (package.json states v1.1) and Kirby version 2.4.1.

**Comment by TimOetting** [comment]
Okay, strange. So, in your case the discard/save buttons are simply not hidden as you can see it in this gif? https://raw.githubusercontent.com/TimOetting/kirby-builder/master/PREVIEW.gif

**Comment by wout** [comment]
That the case indeed. Here is a screenshot:

![screen shot 2017-01-25 at 15 30 31](https://cloud.githubusercontent.com/assets/107324/22294352/509fc0d4-e313-11e6-977c-71b714df8d04.png)

No errors in the browser console either (e.g. failing javascript).

**Comment by TimOetting** [comment]
Alright, that's not intended. As far as I could see it by now, my installation on Kirby 2.4 works. I will have a closer look on that topic the next days.

Thanks for the hint.

**Comment by wout** [comment]
Great, thanks!

For what it's worth, I've got the following fields installed:
- builder
- country
- wysiwyg

And the following plugins:
- autoid
- autopublish
- oembed
- scssphp
- twig
- uniform

Maybe it's one of them causing the trouble.

**Comment by macx** [comment]
Same here, with the newest versions.

**Comment by sen-zo** [comment]
The Problem is caused by a hard-coded class name in builder.js:115,126,146. `'.form-blueprint-project'` is a generated class name where 'project' refers to the blueprint name. In my case, the class name looks like this: `.form-blueprint-builder`. We need another way to identify the main save button. See #38

**Comment by TimOetting** [comment]
Hey all together! I fixed the issue. The save bar will now be hidden on any kind of site type during edit mode.

**Comment by sen-zo** [comment]
Hey, I closed my pull request. Please consider to check the other occurrences of `var mainForm = $('.form-blueprint-project')`.
