### ISSUE TITLE
When adding the same block twice without reloading admin page the same content is used for the new block

### ISSUE THREAD

**Issue by ghost** [TimOetting/kirby-builder#39]
![selection_015](https://cloud.githubusercontent.com/assets/7044512/22645751/dc7df310-ec68-11e6-80df-d4830831787f.png)

I expected a new block to always be completely clean from data.
Hopefully it's not one of my other plugins that causes this have not yet tried on a clean install.

Additional Plugins/Fields used:
kirby-focus
gallerygrid
yakme
jumplist

Thanks for the plugin!

**Comment by TimOetting** [comment]
This issue is related to old version for Kirby 2 and will therefore not be fixed anymore. I am currently closing all the old reports to clean up the the issues section here on github.
