### ISSUE TITLE
Incompatible with Kirby v2.2 Beta

### ISSUE THREAD

**Issue by dionysiusmarquis** [TimOetting/kirby-builder#4]
The builder is currently not compatible with the current develop branch of Kirby.

``PHP Fatal error:  Class 'blueprint' not found in .../site/fields/builder/builder.php on line 75``

**Comment by dionysiusmarquis** [comment]
Could you create a ``develop`` branch? I forked and rebuild the whole ``builder`` field. You can see it here: https://github.com/dionysiusmarquis/kirby-builder/tree/develop. I would like to merge, but not into your ``master`` branch because it's only working with Kirby Panel v2.2 beta.

**Comment by TimOetting** [comment]
Hey dionysiusmarquis, thanks for your assistance. I created a develop branch.
