### ISSUE TITLE
Panel breaks if a user delete an image which is still used in a builder field

### ISSUE THREAD

**Issue by kaloja** [TimOetting/kirby-builder#41]
If a user delete an image from the page which is still in use on a builder field, the panel breaks. It's not possible for the user to solve this issue from the panel because the user can't upload the image again when all the panel logic are gone.

I'm using Kirby v2.4.1 and Kirby Builder v1.0.0.

To solve this bug I had to remove the image manually from the page txt-file inside the content directory. 

I think this is a major bug, because if a user does this it can't be solved until a developer changed the txt-file on the server.

`Method BuilderField::__toString() must not throw an exception, caught Error: Call to a member function url() on null`

**Comment by kaloja** [comment]
I found a solution: https://getkirby.com/docs/cheatsheet/file/exists

Always check if the file exist before echo the code. 

```
<?php if($data->image()->exists()): ?>
    <img class="c-feature-image c-feature-image--left" src="<?= $data->image()->toFile()->url() ?>">
<?php endif ?>
```

**Comment by bugsysop** [comment]
In the context of à Builder Field the solution is:

````
<?php $image = $page->image($data->my_img()); ?>
  <?php if($image): ?>
  <img src="<?= $image->url() ?>" />
<?php endif ?>
````

Indication found here : https://getkirby.com/docs/cookbook/handling-images-in-kirby

**Comment by jackfowler** [comment]
This fix seems to work on the front end (in my template file), but still throws an error when editing the page in the panel. Sorry if I'm missing something here. Any help would be really appreciated.

**Comment by TimOetting** [comment]
This issue is related to old version for Kirby 2 and will therefore not be fixed anymore. I am currently closing all the old reports to clean up the the issues section here on github.
