### ISSUE TITLE
Kirby Page Builder on multilingual pages

### ISSUE THREAD

**Issue by vschaefer** [TimOetting/kirby-builder#45]
Hello,

I use the Kirby Page Builder on a multilingual website.
If I add a content block in the backend in the default language, is it possible to automatically create a copy of the block in the other languages?

**Comment by TimOetting** [comment]
This issue is related to old version for Kirby 2 and will therefore not be fixed anymore. I am currently closing all the old reports to clean up the the issues section here on github.
