### ISSUE TITLE
fields not previewed in panel at all

### ISSUE THREAD

**Issue by luckystairs** [TimOetting/kirby-builder#47]
I'm using default install of builder and everything seems to work but i get no preview – the content block is there with its edit and delete buttons and when i click edit the saved content is in there but there's no preview of it. I tried some of the techniques for customising preview (eg entry: >   <i>"{{text}}"</i></br></br>  {{citation}}  etc.) but no luck either. Any ideas what's wrong? Thanks.

**Comment by TimOetting** [comment]
Hey @luckystairs

Can you give me the entire builder path of you blueprint?

**Comment by luckystairs** [comment]
Ahhh... that's made me see my error – incorrect snippet paths. All good now – and thanks.
