### ISSUE TITLE
Global field extends

### ISSUE THREAD

**Issue by bnomei** [TimOetting/kirby-builder#48]
I wanted to use global fields to bring more structure into my fieldset but it does not seem to work. am I missing something or does it simply not work? 

maybe use or port that feature from @jenstornell?
https://github.com/jenstornell/kirby-blueprint-reader

**Comment by dionysiusmarquis** [comment]
Is this related: https://github.com/TimOetting/kirby-builder/issues/8?

**Comment by bnomei** [comment]
yes. using `extends` instead of the shorthand version works. thanks.

```yml
myfield:
  extends: globalfielddef
```
