### ISSUE TITLE
storing snippets in plugin

### ISSUE THREAD

**Issue by bnomei** [TimOetting/kirby-builder#49]
... does not work without setting the config `buildersnippets.path`. why use `str::tpl` instead of the `snippet()`-helper?

https://github.com/TimOetting/kirby-builder/blob/master/builder.php#L43

**Comment by WeTurkstra** [comment]
I think because the snippet helper is only used in the frontend. And ultimately  it uses tpl::load. And this way you can set a custom snippet path for your builder snippets. But if you dont set it will use the default snippet location

**Comment by bnomei** [comment]
problem is one can not create a custom plugin to bundle code for kirby-builder. 

all snippets have to be copied to `/site/snippets`. registering snippet via plugin does not apply if `str::tpl` is used directly. currently it just breaks the logic what a snippet is. a bit silly imho if just using `snippet()` would do the trick.

is setting a custom folder worth breaking default kirby logic?

**Comment by TimOetting** [comment]
This issue is related to old version for Kirby 2 and will therefore not be fixed anymore. I am currently closing all the old reports to clean up the the issues section here on github.
