### ISSUE TITLE
how to limit use of fieldsets

### ISSUE THREAD

**Issue by bnomei** [TimOetting/kirby-builder#50]
is there any way to limit how often a fieldset can be used?

**Comment by tasinttttttt** [comment]
Here's a quick fix — quick meaning it just hides the add button when the max number of fieldsets is reached.

1. In your blueprint, add `limit: 2` or any number of max entries you want, just like in a regular structure field.

2. In the `site/fields/builder` folder, edit the `template.php` file, add `<?php if ( !$field->limit() || ($field->entries()->count() < $field->limit())): ?>` before the `<div class="builder-add-buttons">` tag, and don't forget to add `<?php endif; ?>` just before the last `</div>`.

It should look something like
```
<?php if ( !$field->limit() || ($field->entries()->count() < $field->limit())): ?>
  <div class="builder-add-buttons">
    <?php foreach ($field->fieldsets as $fieldsetName => $fieldset):
      $fieldset = $field->fieldset($fieldsetName);
    ?>
      <a class="btn btn-rounded" data-quickform href="#" data-href="<?= purl($field->page, 'field/' . $field->name . '/builder/add?fieldset=' . $fieldsetName) ?>"><i class="icon icon-left fa fa-plus-circle"></i><?= $fieldset->label ?></a>
    <?php endforeach ?>
  </div>
<?php endif; ?>
```
