### ISSUE TITLE
Add a note not to use camelCase in builder field names

### ISSUE THREAD

**Issue by texnixe** [TimOetting/kirby-builder#52]
(and change the example field names). This might [lead to problems with filenames in some environments](https://forum.getkirby.com/t/snippet-not-working-on-domain/7884/39), we recommend using lowercase filenames only.

**Comment by TimOetting** [comment]
This issue is related to old version for Kirby 2 and will therefore not be fixed anymore. I am currently closing all the old reports to clean up the the issues section here on github.
