### ISSUE TITLE
Combine with Patterns plugin?

### ISSUE THREAD

**Issue by Cuboctaedro** [TimOetting/kirby-builder#58]
Is it possible to combine Builder with the Patterns plugin and use a pattern instead of a snippet to preview content?
I have tried to set `buildersnippets.path `to a directory inside patterns but it does not seem to work (I don't see any previews).
I have also tried to call a pattern inside the preview snippet but this seems to cause some major havoc in the entire form.

**Comment by Cuboctaedro** [comment]
Update: It actually works perfectly with `buildersnippets.path`, I must have been doing something wrong. The only thing to note is that since pattern files are named with the format `filename.html.php` the `.html` should be included in the snippet name in the blueprint.

**Comment by TimOetting** [comment]
This issue is related to old version for Kirby 2 and will therefore not be fixed anymore. I am currently closing all the old reports to clean up the the issues section here on github.
