### ISSUE TITLE
Indented lists not working correctly

### ISSUE THREAD

**Issue by foobartel** [TimOetting/kirby-builder#59]
When entering an indented list, it seems that builder doesn’t correctly honor the spaces and strips them out, hence indented list items appear as regular list items without indentation. 

Example: 

```
- first list item
    - indented list item
- indented list item
```

The above markdown results in: 

```
<ul>
  <li>first list item</li>
  <li>indented list item</li>
  <li>indented list item</li>
</ul>
```

**Comment by TimOetting** [comment]
This issue is related to old version for Kirby 2 and will therefore not be fixed anymore. I am currently closing all the old reports to clean up the the issues section here on github.
