### ISSUE TITLE
Compartibility with kirby 3

### ISSUE THREAD

**Issue by theWeird** [TimOetting/kirby-builder#61]
Anyone already used this plugin in kirby 3?

I am trying to migrate a page using this field to kirby 3, but with installation of this field in site/fields, kirby tells me: 
![image](https://user-images.githubusercontent.com/165980/49902565-8d8fdb00-fe64-11e8-9ab4-dc8b011c4923.png)

So I wonder if ...
- anyone got the current version up and running in kirby 3
- Tim plans to migrate this really useful plugin to kirby 3

**Comment by TimOetting** [comment]
Hey @theWeird,

Have a look at https://github.com/TimOetting/kirby-v3-builder . That's the repo for the new version of the Kirby builder. It is still in beta state, keep that in mind :)
