### ISSUE TITLE
[Bug] 'Max' Option Still Allows Further Adding of Blocks

### ISSUE THREAD

**Issue by luxlogica** [TimOetting/kirby-builder#64]
The `max` option is currently not limiting the amount of blocks that can be added to the builder field. When we set a `max`, and the maximum number of blocks is reached, it hides the 'Add' button from the bottom of the builder. However, the **dotted line**, which shows between blocks and at the top of the field, is still displayed, and when clicked _still adds a new block_.

<img width="881" alt="screen shot 2019-01-18 at 7 08 57 am" src="https://user-images.githubusercontent.com/2994472/51345874-3ed30200-1af0-11e9-8a17-279da8f86c2d.png">

**Comment by TimOetting** [comment]
solved, thanks for the contribution
