### ISSUE TITLE
Cannot render block snippets at all (local dev)

### ISSUE THREAD

**Issue by macx** [TimOetting/kirby-builder#68]
In my template I'm using the following code to show the blocks, but it didn't work. The problem: `$block->_key_()` is empty. I'm using the yaml I posted in #67.

```php
  <?php foreach($page->builder()->toBuilderBlocks() as $block): ?>
    <?php snippet('blocks/' . $block->_key_(), array('data' => $block)) ?>
  <?php endforeach ?>
```

`$page->builder()->toBuilderBlocks()` will return this:

```html
Kirby\Cms\Structure Object
(
    [0] => 0
)
```

For me at the moment, the builder doesn't work at all. Don't know why.

**Comment by jschopplich** [comment]
I guess that's a typo in the README. It should be `_key()` without a second underscore.

**Comment by macx** [comment]
@jschopplich It is. thanks!

**Comment by TimOetting** [comment]
Thanks, I just merged the pull request
