### ISSUE TITLE
Browser jumps to top if no file is selectet

### ISSUE THREAD

**Issue by thomasfahrland** [TimOetting/kirby-builder#72]
If a page contains no files and I click on the file or picture button in the editor, the browser jumps up.

![screencast 2019-01-24 10-19-18](https://user-images.githubusercontent.com/24317084/51668174-e7d29e80-1fc1-11e9-9f9d-60be5f99269c.gif)

kirby-builder: latest (548b46d) and also older version
Kirby: 3.0.0
Mac OSX, Google Chrome latest (70.x)

**Comment by thomasfahrland** [comment]
thx for fixing. Have tested it successfully.

**Comment by TimOetting** [comment]
@thomasfahrland dumb question, but how to you get these buttons? I can not find anything at the docs https://getkirby.com/docs/reference/panel/fields/textarea and they are not showing up by default

**Comment by thomasfahrland** [comment]
Have testet it now without the builder plugin. Sorry - it's a bug in kirby-markdown-field.
