### ISSUE TITLE
Always default to 'preview' mode.

### ISSUE THREAD

**Issue by louiswalch** [TimOetting/kirby-builder#79]
Is is possible to default all builder sections to the 'preview' mode when first viewing a page, no matter what was the last tab the user was in? This would be incredibly nice to have a cleaner initial view until the user decides to edit a section (similar to how the Kirby 2 Builder was).

**Comment by yordanoff** [comment]
This would be great!

**Comment by flokosiol** [comment]
… would be even better, if this could be an option in the blueprint.

**Comment by jesuismaxime** [comment]
Definitely a must. I loved the Builder in Kirby2 because of that. A blueprint option to choose your default tab would be cool too.

```
my-block:
	label: My block
	preview:
		snippet: '_builder/blocks/my-block'
	default: tab-settings # or `preview`
	tabs:
		### Tab: Content
		tab-content:
			label: Content
			fields:
				...

		### Tab: Settings
		tab-settings:
			label: Settings
			fields:
				...
```

**Comment by mrflix** [comment]
You can enable always on previews by setting `showPreview` to `true` in `BuilderBlock.vue:161`: 

![image](https://user-images.githubusercontent.com/60777/56572379-3f7fa680-65bf-11e9-9567-a146f6fc0a34.png)

After the change you have to rebuild the plugin:

1. Run `npm install` (or `yarn install`) in `site/plugins/builder` (if you don't have npm or yarn installed you'll have to do that first)
2. Then run `npm run build`

**Comment by TimOetting** [comment]
Hey everyone,

I just added the option `defaultView` that can be defined per fieldset. It can contain either the name of a tab or the phrase "preview". If set, the respective tab or the preview mode is opened on page load. This feature does not affect newly created block because I consider it to be more more useful to start new blocks in edit mode until they are filled with content.

Please have a look at this feature and tell me if it works as required for you.

**Comment by flokosiol** [comment]
Works for me. Thanks a lot! 

But I had one little issue (probably not related): I couldn't update via `composer update …`. Unfortunately I forgot to screenshot the error 🤦‍♂  I had to remove the plugin entirely and add it again with copy/paste into the `plugins` folder.

**Comment by TimOetting** [comment]
I pushed a fix for the composer check. Could you please check if this solves your problem?
