### ISSUE TITLE
Panel: Add field name to the block template

### ISSUE THREAD

**Issue by macx** [TimOetting/kirby-builder#82]
In the kirby-builder for Kirby2 you have added the fieldnames to the blocks as classnames (`builder-entry-price`, if `price` is the name). With this extra classes I could style the blocks using a panel.css to give users a better UX of the available blocks:

![image](https://user-images.githubusercontent.com/84112/51905642-0968c700-23c2-11e9-8cee-079616a349be.png)

Could you please add them to the V3 version as well?

I see other plugins using `v-bind="$props"` to add them, but my Vue knowledge is to poor to create a pull request.

**Comment by TimOetting** [comment]
Hey @macx 

the builder blocks now have an additional class `kBuilderBlock--type-[your block name]`

Pro tip: Maybe the class will change to `k-builder-block--type-[your block name]` in the future

**Comment by macx** [comment]
@TimOetting Do you have any plans for the release date? I can't update via composer without a new release (I think).

**Comment by TimOetting** [comment]
I increased the version inside the composer.json just a minute ago. Does this do the trick?

**Comment by macx** [comment]
@TimOetting Unfortunately not. `composer update` and `composer update vendor/timoetting/kirby-builder` doesn't work.

**Comment by TimOetting** [comment]
I think I managed to understand how to get the latest version to packagist. Could you try again to update?

**Comment by macx** [comment]
@TimOetting Worked perfectly after a `composer clearcache`. Now it's the version 2.0.2. Thank you!

**Comment by TimOetting** [comment]
I added `kBuilder__addBlockButton--[your block name] to the buttons.
