### ISSUE TITLE
Checkbox

### ISSUE THREAD

**Issue by mungle** [TimOetting/kirby-builder#84]
Hello! I have a checkbox in a style tab but I'm unable to get the output...

If I add `<?php dump($data->padding()) ?>` in my snippet (that works with other field) I get

```
Kirby\Cms\Field Object
(
    [padding] => Array
        (
            [0] => top
            [1] => bottom
        )

)
```

But if I add

`  <?php foreach ($data->padding()->split() as $padding): echo $padding.' '; endforeach; ?>`

I get 

_**Whoops \ Exception \ ErrorException (E_NOTICE)
Array to string conversion**_

Any help?
thank you!

**Comment by mungle** [comment]
The solution is:

```
<?php
foreach ($data->padding() as $element):
  foreach ($element as $element):
    echo $element.' ';
  endforeach;
endforeach;
?>
```

**Comment by TimOetting** [comment]
@mungle I pushed a bugfix that should also fix your issue. Could you please test it?

**Comment by mungle** [comment]
Perfect...! Thank you!
