### ISSUE TITLE
Problems on Kirby 2.2.3

### ISSUE THREAD

**Issue by Constantin-Gololobov** [TimOetting/kirby-builder#9]
Hi, Tim!
Thank you for you plugin!
Is it works fine on the last Kirby version?

**Comment by TimOetting** [comment]
Hi Constantin,
yes, it should work with the newest version of Kirby. Did you have problems with the plugin?

**Comment by Constantin-Gololobov** [comment]
Yep!
But I think that I will find what the problem.
Thank you)

**Comment by Constantin-Gololobov** [comment]
I find a problem!
In blueprint i write this (like in your example):

fields:
...
builder:
   ...

But for work properly this structure is correct:
fields:
...
   builder:
   ...

**Comment by TimOetting** [comment]
The texts are the same in your comment ;) But I assume you mean the unclear indentation like this ?: 

Instead of

    fields:
    ...
    builder:
    ...

it should be

    fields:
    ...
      builder:
      ...

I will fix that asap.

**Comment by Constantin-Gololobov** [comment]
Yes, this right.
Thank you!
