### ISSUE TITLE
Error on duplication of content blocks, if not saved

### ISSUE THREAD

**Issue by bavarianbytes** [TimOetting/kirby-builder#96]
Error message if i a create or change a content block and choose "Duplicate" from the menu of the block BEFORE i hit "save".

<img width="1460" alt="bildschirmfoto 2019-03-08 um 17 40 54" src="https://user-images.githubusercontent.com/17915115/54049252-4c496600-41dc-11e9-8a29-8bc72a9a59ce.png">

**Comment by TimOetting** [comment]
Hey @bavarianbytes,

can you please check if this error still occurs with the latest version of the kirby builder?

**Comment by bavarianbytes** [comment]
Doesn't seem to occur anymore! Thx
