### ISSUE TITLE
Tabs in panel show text overflow on small devices

### ISSUE THREAD

**Issue by bavarianbytes** [TimOetting/kirby-builder#97]
<img width="451" alt="bildschirmfoto 2019-03-08 um 20 06 25" src="https://user-images.githubusercontent.com/17915115/54049777-cb8b6980-41dd-11e9-9914-a8876e29ec11.png">

Text wrapping with multiline tab items?

**Comment by TimOetting** [comment]
Hey @bavarianbytes ,

Version 2.0.13 has just been released. The Header bar now wraps if needed.
